# -*- coding: utf-8 -*-
"""Detective hate speech

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__CocZdkgCcDp5Q29gxX3eBRkzh8Upsv
"""

import pandas as pd

offensive_words = ["hate", "violence", "attack", "racist", "sexist"]

#Function to detect hate speech
def detect_hate_speech(text):
  detected_words = [word for word in offensive_words if word in text.lower()]
  return detected_words

#Example usage
text= "The Tutsis are like cockroaches, they must be exterminated, they must be killed, and we, the Hutus, will be the ones to do it."
hate_words = detect_hate_speech(text)
if hate_words:
    print("Offensive words:", hate_words)
else:
    print("No hate speech detected.")